CREATE TABLE CUSTOMERS (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255) NOT NULL,
	age INT(3) NOT NULL,
	phone_number VARCHAR(10),
	PRIMARY KEY (id),
	UNIQUE INDEX id (id)
)
COLLATE='utf8mb4_0900_ai_ci';